### ISSUE TITLE
Error when resource yaml is wrong

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-tekton#34]
By using this yaml
```
spec:
  params:
    - name: flags
      type: array
    - name: someURL
      type: string
  steps:
    - name: build
      image: my-builder
      args: ["build", "$(params.flags[*])", "url=$(params.someURL)"]
```

the saving fails with this error 
```
io.fabric8.kubernetes.client.KubernetesClientException: Error while performing the call to https://api.crc.testing:6443/apis/tekton.dev/v1alpha1/namespaces/pipeline-test/tasks/. Response code: 500
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:582)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:593)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.create(RawCustomResourceOperationsImpl.java:122)
	at com.redhat.devtools.intellij.tektoncd.tkn.TknCli.createCustomResource(TknCli.java:171)
```

Now, by trying it with the terminal i got a clearer message

```
Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"
```

All of this to say.... we should show an error which is more explanatory

**Comment by lstocchi** [comment]
Another example of this is when there is a non-existent variable
E.g
```
apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: foocluster
spec:
  steps:
  - image: ubuntu
  - args:
    - $(inputs.params.ARGS)
    command:
    - /usr/local/bin/tkn
    image: $(inputs.params.tkn-image)
    name: tkn
    resources: {}
```
```
Error from server (InternalError): error when creating "/home/luca/Public/github.com/redhat-developer/intellij-tekton/build/idea-sandbox/config/scratches/newclustertask.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: non-existent variable in "$(inputs.params.tkn-image)" for step image: taskspec.steps.image

```

**Comment by lstocchi** [comment]
Closing it as we agreed these are server issues and the plugin only needs to show the error received as it is now
